//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Jhooa.UI.Features.Identity.Resources {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Identity {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Identity() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Jhooa.UI.Features.Identity.Resources.Identity", typeof(Identity).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string CreateAccount {
            get {
                return ResourceManager.GetString("CreateAccount", resourceCulture);
            }
        }
        
        internal static string FormEmail {
            get {
                return ResourceManager.GetString("FormEmail", resourceCulture);
            }
        }
        
        internal static string FormPassword {
            get {
                return ResourceManager.GetString("FormPassword", resourceCulture);
            }
        }
        
        internal static string FormRememberMe {
            get {
                return ResourceManager.GetString("FormRememberMe", resourceCulture);
            }
        }
        
        internal static string FormLogin {
            get {
                return ResourceManager.GetString("FormLogin", resourceCulture);
            }
        }
        
        internal static string ForgotPassword {
            get {
                return ResourceManager.GetString("ForgotPassword", resourceCulture);
            }
        }
        
        internal static string AlreadyHaveAccount {
            get {
                return ResourceManager.GetString("AlreadyHaveAccount", resourceCulture);
            }
        }
        
        internal static string ResetPassword {
            get {
                return ResourceManager.GetString("ResetPassword", resourceCulture);
            }
        }
        
        internal static string RegisterIntro {
            get {
                return ResourceManager.GetString("RegisterIntro", resourceCulture);
            }
        }
        
        internal static string RegisterMyWishes {
            get {
                return ResourceManager.GetString("RegisterMyWishes", resourceCulture);
            }
        }
        
        internal static string RegisterMySub {
            get {
                return ResourceManager.GetString("RegisterMySub", resourceCulture);
            }
        }
        
        internal static string RegisterButton {
            get {
                return ResourceManager.GetString("RegisterButton", resourceCulture);
            }
        }
        
        internal static string FormLastName {
            get {
                return ResourceManager.GetString("FormLastName", resourceCulture);
            }
        }
        
        internal static string FormFirstName {
            get {
                return ResourceManager.GetString("FormFirstName", resourceCulture);
            }
        }
        
        internal static string FormPasswordVerification {
            get {
                return ResourceManager.GetString("FormPasswordVerification", resourceCulture);
            }
        }
        
        internal static string FormAddress {
            get {
                return ResourceManager.GetString("FormAddress", resourceCulture);
            }
        }
        
        internal static string FormZipCode {
            get {
                return ResourceManager.GetString("FormZipCode", resourceCulture);
            }
        }
        
        internal static string FormCountry {
            get {
                return ResourceManager.GetString("FormCountry", resourceCulture);
            }
        }
        
        internal static string FormPhoneNumber {
            get {
                return ResourceManager.GetString("FormPhoneNumber", resourceCulture);
            }
        }
        
        internal static string RegisterDreamSubTitle {
            get {
                return ResourceManager.GetString("RegisterDreamSubTitle", resourceCulture);
            }
        }
        
        internal static string RegisterDreamDescription {
            get {
                return ResourceManager.GetString("RegisterDreamDescription", resourceCulture);
            }
        }
        
        internal static string RegisterMySubSubTitle {
            get {
                return ResourceManager.GetString("RegisterMySubSubTitle", resourceCulture);
            }
        }
        
        internal static string RegisterMySubDescription {
            get {
                return ResourceManager.GetString("RegisterMySubDescription", resourceCulture);
            }
        }
        
        internal static string RegisterMonthly {
            get {
                return ResourceManager.GetString("RegisterMonthly", resourceCulture);
            }
        }
        
        internal static string RegisterMonthlyRecurring {
            get {
                return ResourceManager.GetString("RegisterMonthlyRecurring", resourceCulture);
            }
        }
        
        internal static string FormSmallDream {
            get {
                return ResourceManager.GetString("FormSmallDream", resourceCulture);
            }
        }
        
        internal static string FormMediumDream {
            get {
                return ResourceManager.GetString("FormMediumDream", resourceCulture);
            }
        }
        
        internal static string FormBigDream {
            get {
                return ResourceManager.GetString("FormBigDream", resourceCulture);
            }
        }
        
        internal static string RegisterYearly {
            get {
                return ResourceManager.GetString("RegisterYearly", resourceCulture);
            }
        }
        
        internal static string SubscribeToNewsletter {
            get {
                return ResourceManager.GetString("SubscribeToNewsletter", resourceCulture);
            }
        }
        
        internal static string AcceptToc {
            get {
                return ResourceManager.GetString("AcceptToc", resourceCulture);
            }
        }
        
        internal static string RegisterYearlyRecurring {
            get {
                return ResourceManager.GetString("RegisterYearlyRecurring", resourceCulture);
            }
        }
        
        internal static string AccessDenied {
            get {
                return ResourceManager.GetString("AccessDenied", resourceCulture);
            }
        }
        
        internal static string AccessDeniedResource {
            get {
                return ResourceManager.GetString("AccessDeniedResource", resourceCulture);
            }
        }
        
        internal static string ConfirmEmail {
            get {
                return ResourceManager.GetString("ConfirmEmail", resourceCulture);
            }
        }
        
        internal static string ConfirmEmailThankYou {
            get {
                return ResourceManager.GetString("ConfirmEmailThankYou", resourceCulture);
            }
        }
        
        internal static string ConfirmEmailError {
            get {
                return ResourceManager.GetString("ConfirmEmailError", resourceCulture);
            }
        }
        
        internal static string EmailInvalid {
            get {
                return ResourceManager.GetString("EmailInvalid", resourceCulture);
            }
        }
        
        internal static string ForgotPasswordConfirmation {
            get {
                return ResourceManager.GetString("ForgotPasswordConfirmation", resourceCulture);
            }
        }
        
        internal static string ForgotPasswordEmailReset {
            get {
                return ResourceManager.GetString("ForgotPasswordEmailReset", resourceCulture);
            }
        }
        
        internal static string InvalidPasswordReset {
            get {
                return ResourceManager.GetString("InvalidPasswordReset", resourceCulture);
            }
        }
        
        internal static string InvalidPasswordResetLink {
            get {
                return ResourceManager.GetString("InvalidPasswordResetLink", resourceCulture);
            }
        }
        
        internal static string InvalidUser {
            get {
                return ResourceManager.GetString("InvalidUser", resourceCulture);
            }
        }
        
        internal static string LockedOut {
            get {
                return ResourceManager.GetString("LockedOut", resourceCulture);
            }
        }
        
        internal static string LockedOutTryLater {
            get {
                return ResourceManager.GetString("LockedOutTryLater", resourceCulture);
            }
        }
        
        internal static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        internal static string LoginEmailNotConfirmed {
            get {
                return ResourceManager.GetString("LoginEmailNotConfirmed", resourceCulture);
            }
        }
        
        internal static string LoginInvalidAttempt {
            get {
                return ResourceManager.GetString("LoginInvalidAttempt", resourceCulture);
            }
        }
        
        internal static string Required {
            get {
                return ResourceManager.GetString("Required", resourceCulture);
            }
        }
        
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        internal static string Register {
            get {
                return ResourceManager.GetString("Register", resourceCulture);
            }
        }
        
        internal static string EmailAddress {
            get {
                return ResourceManager.GetString("EmailAddress", resourceCulture);
            }
        }
        
        internal static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        internal static string LastName {
            get {
                return ResourceManager.GetString("LastName", resourceCulture);
            }
        }
        
        internal static string FirstName {
            get {
                return ResourceManager.GetString("FirstName", resourceCulture);
            }
        }
        
        internal static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        internal static string ZipCode {
            get {
                return ResourceManager.GetString("ZipCode", resourceCulture);
            }
        }
        
        internal static string Country {
            get {
                return ResourceManager.GetString("Country", resourceCulture);
            }
        }
        
        internal static string PhoneNumber {
            get {
                return ResourceManager.GetString("PhoneNumber", resourceCulture);
            }
        }
        
        internal static string ConfirmPassword {
            get {
                return ResourceManager.GetString("ConfirmPassword", resourceCulture);
            }
        }
        
        internal static string FieldLength {
            get {
                return ResourceManager.GetString("FieldLength", resourceCulture);
            }
        }
        
        internal static string PasswordNotMatching {
            get {
                return ResourceManager.GetString("PasswordNotMatching", resourceCulture);
            }
        }
        
        internal static string RegisterConfirmation {
            get {
                return ResourceManager.GetString("RegisterConfirmation", resourceCulture);
            }
        }
        
        internal static string AccountCreatedAndPaymentDone {
            get {
                return ResourceManager.GetString("AccountCreatedAndPaymentDone", resourceCulture);
            }
        }
        
        internal static string CheckEmailForConfirmation {
            get {
                return ResourceManager.GetString("CheckEmailForConfirmation", resourceCulture);
            }
        }
        
        internal static string Reset {
            get {
                return ResourceManager.GetString("Reset", resourceCulture);
            }
        }
        
        internal static string ResetPasswordConfirmation {
            get {
                return ResourceManager.GetString("ResetPasswordConfirmation", resourceCulture);
            }
        }
        
        internal static string MyAccount {
            get {
                return ResourceManager.GetString("MyAccount", resourceCulture);
            }
        }
        
        internal static string MyDreams {
            get {
                return ResourceManager.GetString("MyDreams", resourceCulture);
            }
        }
        
        internal static string MySubscription {
            get {
                return ResourceManager.GetString("MySubscription", resourceCulture);
            }
        }
        
        internal static string SaveChanges {
            get {
                return ResourceManager.GetString("SaveChanges", resourceCulture);
            }
        }
        
        internal static string ChangePassword {
            get {
                return ResourceManager.GetString("ChangePassword", resourceCulture);
            }
        }
        
        internal static string UpdatePassword {
            get {
                return ResourceManager.GetString("UpdatePassword", resourceCulture);
            }
        }
        
        internal static string OldPassword {
            get {
                return ResourceManager.GetString("OldPassword", resourceCulture);
            }
        }
        
        internal static string NewPassword {
            get {
                return ResourceManager.GetString("NewPassword", resourceCulture);
            }
        }
        
        internal static string ConfirmNewPassword {
            get {
                return ResourceManager.GetString("ConfirmNewPassword", resourceCulture);
            }
        }
        
        internal static string PasswordChanged {
            get {
                return ResourceManager.GetString("PasswordChanged", resourceCulture);
            }
        }
        
        internal static string SmallDreamPlaceholder {
            get {
                return ResourceManager.GetString("SmallDreamPlaceholder", resourceCulture);
            }
        }
        
        internal static string MediumDreamPlaceholder {
            get {
                return ResourceManager.GetString("MediumDreamPlaceholder", resourceCulture);
            }
        }
        
        internal static string BigDreamPlaceholder {
            get {
                return ResourceManager.GetString("BigDreamPlaceholder", resourceCulture);
            }
        }
        
        internal static string France {
            get {
                return ResourceManager.GetString("France", resourceCulture);
            }
        }
        
        internal static string Belgium {
            get {
                return ResourceManager.GetString("Belgium", resourceCulture);
            }
        }
        
        internal static string Luxembourg {
            get {
                return ResourceManager.GetString("Luxembourg", resourceCulture);
            }
        }
        
        internal static string AcceptDiffusion {
            get {
                return ResourceManager.GetString("AcceptDiffusion", resourceCulture);
            }
        }
        
        internal static string AcceptDiffusionDesc {
            get {
                return ResourceManager.GetString("AcceptDiffusionDesc", resourceCulture);
            }
        }
        
        internal static string City {
            get {
                return ResourceManager.GetString("City", resourceCulture);
            }
        }
        
        internal static string BirthDate {
            get {
                return ResourceManager.GetString("BirthDate", resourceCulture);
            }
        }
        
        internal static string SubType {
            get {
                return ResourceManager.GetString("SubType", resourceCulture);
            }
        }
        
        internal static string SmallDream {
            get {
                return ResourceManager.GetString("SmallDream", resourceCulture);
            }
        }
        
        internal static string AcceptDistribution {
            get {
                return ResourceManager.GetString("AcceptDistribution", resourceCulture);
            }
        }
        
        internal static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
        
        internal static string NewsletterAccepted {
            get {
                return ResourceManager.GetString("NewsletterAccepted", resourceCulture);
            }
        }
        
        internal static string AlreadyHaveAccountQuestion {
            get {
                return ResourceManager.GetString("AlreadyHaveAccountQuestion", resourceCulture);
            }
        }
        
        internal static string InsertDreams {
            get {
                return ResourceManager.GetString("InsertDreams", resourceCulture);
            }
        }
        
        internal static string EmailResetPasswordSubject {
            get {
                return ResourceManager.GetString("EmailResetPasswordSubject", resourceCulture);
            }
        }
        
        internal static string EmailResetPasswordTitle {
            get {
                return ResourceManager.GetString("EmailResetPasswordTitle", resourceCulture);
            }
        }
        
        internal static string EmailResetPasswordContent {
            get {
                return ResourceManager.GetString("EmailResetPasswordContent", resourceCulture);
            }
        }
        
        internal static string EmailAccountConfirmationSubject {
            get {
                return ResourceManager.GetString("EmailAccountConfirmationSubject", resourceCulture);
            }
        }
        
        internal static string EmailAccountConfirmationTitle {
            get {
                return ResourceManager.GetString("EmailAccountConfirmationTitle", resourceCulture);
            }
        }
        
        internal static string EmailAccountConfirmationContent {
            get {
                return ResourceManager.GetString("EmailAccountConfirmationContent", resourceCulture);
            }
        }
        
        internal static string TermsMustBeAccepted {
            get {
                return ResourceManager.GetString("TermsMustBeAccepted", resourceCulture);
            }
        }
        
        internal static string ExportNewsletter {
            get {
                return ResourceManager.GetString("ExportNewsletter", resourceCulture);
            }
        }
        
        internal static string ExportFull {
            get {
                return ResourceManager.GetString("ExportFull", resourceCulture);
            }
        }
        
        internal static string All {
            get {
                return ResourceManager.GetString("All", resourceCulture);
            }
        }
        
        internal static string Admin {
            get {
                return ResourceManager.GetString("Admin", resourceCulture);
            }
        }
        
        internal static string Active {
            get {
                return ResourceManager.GetString("Active", resourceCulture);
            }
        }
        
        internal static string Inactive {
            get {
                return ResourceManager.GetString("Inactive", resourceCulture);
            }
        }
        
        internal static string Filters {
            get {
                return ResourceManager.GetString("Filters", resourceCulture);
            }
        }
        
        internal static string Code {
            get {
                return ResourceManager.GetString("Code", resourceCulture);
            }
        }
        
        internal static string CodeRequired {
            get {
                return ResourceManager.GetString("CodeRequired", resourceCulture);
            }
        }
        
        internal static string CodeNotValid {
            get {
                return ResourceManager.GetString("CodeNotValid", resourceCulture);
            }
        }
        
        internal static string ResetPasswordInvalidAttempt {
            get {
                return ResourceManager.GetString("ResetPasswordInvalidAttempt", resourceCulture);
            }
        }
    }
}
