//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Jhooa.UI.Features.Identity.Resources {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Identity {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Identity() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Jhooa.UI.Features.Identity.Resources.Identity", typeof(Identity).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string CreateAccount {
            get {
                return ResourceManager.GetString("CreateAccount", resourceCulture);
            }
        }
        
        internal static string FormEmail {
            get {
                return ResourceManager.GetString("FormEmail", resourceCulture);
            }
        }
        
        internal static string FormPassword {
            get {
                return ResourceManager.GetString("FormPassword", resourceCulture);
            }
        }
        
        internal static string FormRememberMe {
            get {
                return ResourceManager.GetString("FormRememberMe", resourceCulture);
            }
        }
        
        internal static string FormLogin {
            get {
                return ResourceManager.GetString("FormLogin", resourceCulture);
            }
        }
        
        internal static string ForgotPassword {
            get {
                return ResourceManager.GetString("ForgotPassword", resourceCulture);
            }
        }
        
        internal static string AlreadyHaveAccount {
            get {
                return ResourceManager.GetString("AlreadyHaveAccount", resourceCulture);
            }
        }
        
        internal static string ResetPassword {
            get {
                return ResourceManager.GetString("ResetPassword", resourceCulture);
            }
        }
        
        internal static string RegisterIntro {
            get {
                return ResourceManager.GetString("RegisterIntro", resourceCulture);
            }
        }
        
        internal static string RegisterMyWishes {
            get {
                return ResourceManager.GetString("RegisterMyWishes", resourceCulture);
            }
        }
        
        internal static string RegisterMySub {
            get {
                return ResourceManager.GetString("RegisterMySub", resourceCulture);
            }
        }
        
        internal static string RegisterButton {
            get {
                return ResourceManager.GetString("RegisterButton", resourceCulture);
            }
        }
        
        internal static string FormLastName {
            get {
                return ResourceManager.GetString("FormLastName", resourceCulture);
            }
        }
        
        internal static string FormFirstName {
            get {
                return ResourceManager.GetString("FormFirstName", resourceCulture);
            }
        }
        
        internal static string FormPasswordVerification {
            get {
                return ResourceManager.GetString("FormPasswordVerification", resourceCulture);
            }
        }
        
        internal static string FormAddress {
            get {
                return ResourceManager.GetString("FormAddress", resourceCulture);
            }
        }
        
        internal static string FormZipCode {
            get {
                return ResourceManager.GetString("FormZipCode", resourceCulture);
            }
        }
        
        internal static string FormCountry {
            get {
                return ResourceManager.GetString("FormCountry", resourceCulture);
            }
        }
        
        internal static string FormPhoneNumber {
            get {
                return ResourceManager.GetString("FormPhoneNumber", resourceCulture);
            }
        }
        
        internal static string RegisterDreamSubTitle {
            get {
                return ResourceManager.GetString("RegisterDreamSubTitle", resourceCulture);
            }
        }
        
        internal static string RegisterDreamDescription {
            get {
                return ResourceManager.GetString("RegisterDreamDescription", resourceCulture);
            }
        }
        
        internal static string RegisterMySubSubTitle {
            get {
                return ResourceManager.GetString("RegisterMySubSubTitle", resourceCulture);
            }
        }
        
        internal static string RegisterMySubDescription {
            get {
                return ResourceManager.GetString("RegisterMySubDescription", resourceCulture);
            }
        }
        
        internal static string RegisterMonthly {
            get {
                return ResourceManager.GetString("RegisterMonthly", resourceCulture);
            }
        }
        
        internal static string RegisterMonthlyRecurring {
            get {
                return ResourceManager.GetString("RegisterMonthlyRecurring", resourceCulture);
            }
        }
        
        internal static string FormSmallDream {
            get {
                return ResourceManager.GetString("FormSmallDream", resourceCulture);
            }
        }
        
        internal static string FormMediumDream {
            get {
                return ResourceManager.GetString("FormMediumDream", resourceCulture);
            }
        }
        
        internal static string FormBigDream {
            get {
                return ResourceManager.GetString("FormBigDream", resourceCulture);
            }
        }
        
        internal static string RegisterYearly {
            get {
                return ResourceManager.GetString("RegisterYearly", resourceCulture);
            }
        }
        
        internal static string SubscribeToNewsletter {
            get {
                return ResourceManager.GetString("SubscribeToNewsletter", resourceCulture);
            }
        }
        
        internal static string AcceptToc {
            get {
                return ResourceManager.GetString("AcceptToc", resourceCulture);
            }
        }
        
        internal static string RegisterYearlyRecurring {
            get {
                return ResourceManager.GetString("RegisterYearlyRecurring", resourceCulture);
            }
        }
    }
}
