//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Jhooa.UI.Features.Home.Resources {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Home {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Home() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Jhooa.UI.Features.Home.Resources.Home", typeof(Home).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string OurConcept {
            get {
                return ResourceManager.GetString("OurConcept", resourceCulture);
            }
        }
        
        internal static string OurConceptPart1 {
            get {
                return ResourceManager.GetString("OurConceptPart1", resourceCulture);
            }
        }
        
        internal static string OurConceptPart2 {
            get {
                return ResourceManager.GetString("OurConceptPart2", resourceCulture);
            }
        }
        
        internal static string OurConceptPart3 {
            get {
                return ResourceManager.GetString("OurConceptPart3", resourceCulture);
            }
        }
        
        internal static string OurConceptPart4 {
            get {
                return ResourceManager.GetString("OurConceptPart4", resourceCulture);
            }
        }
        
        internal static string TitleCourage {
            get {
                return ResourceManager.GetString("TitleCourage", resourceCulture);
            }
        }
        
        internal static string EventsPart1 {
            get {
                return ResourceManager.GetString("EventsPart1", resourceCulture);
            }
        }
        
        internal static string EventsPart2 {
            get {
                return ResourceManager.GetString("EventsPart2", resourceCulture);
            }
        }
        
        internal static string OurEvents {
            get {
                return ResourceManager.GetString("OurEvents", resourceCulture);
            }
        }
        
        internal static string ExpTitle {
            get {
                return ResourceManager.GetString("ExpTitle", resourceCulture);
            }
        }
        
        internal static string ExpDescription {
            get {
                return ResourceManager.GetString("ExpDescription", resourceCulture);
            }
        }
        
        internal static string ExpPart1Title {
            get {
                return ResourceManager.GetString("ExpPart1Title", resourceCulture);
            }
        }
        
        internal static string ExpPart1Desc {
            get {
                return ResourceManager.GetString("ExpPart1Desc", resourceCulture);
            }
        }
        
        internal static string ExpPart2Title {
            get {
                return ResourceManager.GetString("ExpPart2Title", resourceCulture);
            }
        }
        
        internal static string ExpPart2Desc {
            get {
                return ResourceManager.GetString("ExpPart2Desc", resourceCulture);
            }
        }
        
        internal static string ExpPart3Title {
            get {
                return ResourceManager.GetString("ExpPart3Title", resourceCulture);
            }
        }
        
        internal static string ExpPart3Desc {
            get {
                return ResourceManager.GetString("ExpPart3Desc", resourceCulture);
            }
        }
        
        internal static string Monthly {
            get {
                return ResourceManager.GetString("Monthly", resourceCulture);
            }
        }
        
        internal static string Yearly {
            get {
                return ResourceManager.GetString("Yearly", resourceCulture);
            }
        }
        
        internal static string PriceMonthlyDesc {
            get {
                return ResourceManager.GetString("PriceMonthlyDesc", resourceCulture);
            }
        }
        
        internal static string PriceYearlyDesc {
            get {
                return ResourceManager.GetString("PriceYearlyDesc", resourceCulture);
            }
        }
        
        internal static string ExpContact {
            get {
                return ResourceManager.GetString("ExpContact", resourceCulture);
            }
        }
    }
}
