//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Jhooa.UI.Features.Videos.Resources {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Videos {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Videos() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Jhooa.UI.Features.Videos.Resources.Videos", typeof(Videos).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string VideosPageTitle {
            get {
                return ResourceManager.GetString("VideosPageTitle", resourceCulture);
            }
        }
        
        internal static string VideosPageText1 {
            get {
                return ResourceManager.GetString("VideosPageText1", resourceCulture);
            }
        }
        
        internal static string VideosPageText2 {
            get {
                return ResourceManager.GetString("VideosPageText2", resourceCulture);
            }
        }
        
        internal static string VideosPageText3 {
            get {
                return ResourceManager.GetString("VideosPageText3", resourceCulture);
            }
        }
        
        internal static string VideosPageText4 {
            get {
                return ResourceManager.GetString("VideosPageText4", resourceCulture);
            }
        }
        
        internal static string TheVideos {
            get {
                return ResourceManager.GetString("TheVideos", resourceCulture);
            }
        }
        
        internal static string Theme {
            get {
                return ResourceManager.GetString("Theme", resourceCulture);
            }
        }
        
        internal static string MonthMonths {
            get {
                return ResourceManager.GetString("MonthMonths", resourceCulture);
            }
        }
        
        internal static string Years {
            get {
                return ResourceManager.GetString("Years", resourceCulture);
            }
        }
        
        internal static string NoVideosFound {
            get {
                return ResourceManager.GetString("NoVideosFound", resourceCulture);
            }
        }
        
        internal static string AddVideo {
            get {
                return ResourceManager.GetString("AddVideo", resourceCulture);
            }
        }
        
        internal static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        internal static string VideoId {
            get {
                return ResourceManager.GetString("VideoId", resourceCulture);
            }
        }
        
        internal static string Themes {
            get {
                return ResourceManager.GetString("Themes", resourceCulture);
            }
        }
        
        internal static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        internal static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        internal static string Actions {
            get {
                return ResourceManager.GetString("Actions", resourceCulture);
            }
        }
        
        internal static string FieldLength {
            get {
                return ResourceManager.GetString("FieldLength", resourceCulture);
            }
        }
        
        internal static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        internal static string EditVideo {
            get {
                return ResourceManager.GetString("EditVideo", resourceCulture);
            }
        }
        
        internal static string Required {
            get {
                return ResourceManager.GetString("Required", resourceCulture);
            }
        }
        
        internal static string VideosOnlyForConnectedUsersTitle {
            get {
                return ResourceManager.GetString("VideosOnlyForConnectedUsersTitle", resourceCulture);
            }
        }
        
        internal static string VideosOnlyForConnectedUsersDesc {
            get {
                return ResourceManager.GetString("VideosOnlyForConnectedUsersDesc", resourceCulture);
            }
        }
        
        internal static string VideosOnlyForConnectedUsersThanks {
            get {
                return ResourceManager.GetString("VideosOnlyForConnectedUsersThanks", resourceCulture);
            }
        }
        
        internal static string VideosOnlyForConnectedUsersAlreadyUsers {
            get {
                return ResourceManager.GetString("VideosOnlyForConnectedUsersAlreadyUsers", resourceCulture);
            }
        }
        
        internal static string VideosOnlyForConnectedUsersRegister {
            get {
                return ResourceManager.GetString("VideosOnlyForConnectedUsersRegister", resourceCulture);
            }
        }
        
        internal static string Months {
            get {
                return ResourceManager.GetString("Months", resourceCulture);
            }
        }
        
        internal static string Month {
            get {
                return ResourceManager.GetString("Month", resourceCulture);
            }
        }
        
        internal static string ChooseTheme {
            get {
                return ResourceManager.GetString("ChooseTheme", resourceCulture);
            }
        }
        
        internal static string ChooseMonth {
            get {
                return ResourceManager.GetString("ChooseMonth", resourceCulture);
            }
        }
        
        internal static string ChooseYear {
            get {
                return ResourceManager.GetString("ChooseYear", resourceCulture);
            }
        }
        
        internal static string VideosOnlyForConnectedUsersDescNoSub {
            get {
                return ResourceManager.GetString("VideosOnlyForConnectedUsersDescNoSub", resourceCulture);
            }
        }
    }
}
