//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Jhooa.UI.Features.Subscriptions.Resources {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Subscriptions {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Subscriptions() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Jhooa.UI.Features.Subscriptions.Resources.Subscriptions", typeof(Subscriptions).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string MySubscription {
            get {
                return ResourceManager.GetString("MySubscription", resourceCulture);
            }
        }
        
        internal static string MySubscriptionTitle {
            get {
                return ResourceManager.GetString("MySubscriptionTitle", resourceCulture);
            }
        }
        
        internal static string MySubscriptionDesc {
            get {
                return ResourceManager.GetString("MySubscriptionDesc", resourceCulture);
            }
        }
        
        internal static string NoActiveSubscription {
            get {
                return ResourceManager.GetString("NoActiveSubscription", resourceCulture);
            }
        }
        
        internal static string ActiveSubscription {
            get {
                return ResourceManager.GetString("ActiveSubscription", resourceCulture);
            }
        }
        
        internal static string AutoRenew {
            get {
                return ResourceManager.GetString("AutoRenew", resourceCulture);
            }
        }
        
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        internal static string Cancelled {
            get {
                return ResourceManager.GetString("Cancelled", resourceCulture);
            }
        }
        
        internal static string SubscriptionRenewed {
            get {
                return ResourceManager.GetString("SubscriptionRenewed", resourceCulture);
            }
        }
    }
}
