//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Jhooa.UI.Resources {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Shared {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Shared() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Jhooa.UI.Resources.Shared", typeof(Shared).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string UsersList {
            get {
                return ResourceManager.GetString("UsersList", resourceCulture);
            }
        }
        
        internal static string Welcome {
            get {
                return ResourceManager.GetString("Welcome", resourceCulture);
            }
        }
        
        internal static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        internal static string Events {
            get {
                return ResourceManager.GetString("Events", resourceCulture);
            }
        }
        
        internal static string DreamsList {
            get {
                return ResourceManager.GetString("DreamsList", resourceCulture);
            }
        }
        
        internal static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        internal static string Type {
            get {
                return ResourceManager.GetString("Type", resourceCulture);
            }
        }
        
        internal static string Small {
            get {
                return ResourceManager.GetString("Small", resourceCulture);
            }
        }
        
        internal static string Medium {
            get {
                return ResourceManager.GetString("Medium", resourceCulture);
            }
        }
        
        internal static string Big {
            get {
                return ResourceManager.GetString("Big", resourceCulture);
            }
        }
        
        internal static string Dreams {
            get {
                return ResourceManager.GetString("Dreams", resourceCulture);
            }
        }
        
        internal static string Dashboard {
            get {
                return ResourceManager.GetString("Dashboard", resourceCulture);
            }
        }
        
        internal static string Users {
            get {
                return ResourceManager.GetString("Users", resourceCulture);
            }
        }
        
        internal static string EmailAddress {
            get {
                return ResourceManager.GetString("EmailAddress", resourceCulture);
            }
        }
        
        internal static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        internal static string FooterContactUs {
            get {
                return ResourceManager.GetString("FooterContactUs", resourceCulture);
            }
        }
        
        internal static string ContactFormSubmit {
            get {
                return ResourceManager.GetString("ContactFormSubmit", resourceCulture);
            }
        }
        
        internal static string ContactFormEmail {
            get {
                return ResourceManager.GetString("ContactFormEmail", resourceCulture);
            }
        }
        
        internal static string ContactFormSubject {
            get {
                return ResourceManager.GetString("ContactFormSubject", resourceCulture);
            }
        }
        
        internal static string ContactFormContent {
            get {
                return ResourceManager.GetString("ContactFormContent", resourceCulture);
            }
        }
        
        internal static string ContactFormConfirmationTitle {
            get {
                return ResourceManager.GetString("ContactFormConfirmationTitle", resourceCulture);
            }
        }
        
        internal static string ContactFormConfirmationDesc {
            get {
                return ResourceManager.GetString("ContactFormConfirmationDesc", resourceCulture);
            }
        }
    }
}
