name: Deploy_WebApp
on:
  workflow_dispatch:
  workflow_run:
    workflows: [Build_WebApp]
    types: [completed]
    branches: [main]

jobs:
  deploy-dev:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    environment:
      name: 'Development'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    
    permissions:
      id-token: write 
      contents: read
      pull-requests: write
      actions: read
    
    steps:
     - name: Download artifact from build job
       uses: dawidd6/action-download-artifact@v6
       with:
         name: release-webapp
         github_token: ${{ github.token }}
         run_id: ${{ github.event.workflow_run.id }}

     - name: Login to Azure
       uses: azure/login@v2
       with:
         creds: ${{ secrets.AZURE_CREDENTIALS_DEV }}

     - name: Deploy to Azure Web App
       id: deploy-to-webapp
       uses: azure/webapps-deploy@v3
       with:
         app-name: 'wapp-jhooa-weu-001'
         slot-name: 'Production'
         package: .

  deploy-production:
    runs-on: ubuntu-latest
    needs: deploy-dev

    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    
    permissions:
      id-token: write 
      contents: read
      pull-requests: write
      actions: read
    
    steps:
     - name: Download artifact from build job
       uses: dawidd6/action-download-artifact@v6
       with:
         name: release-webapp
         github_token: ${{ github.token }}
         run_id: ${{ github.event.workflow_run.id }}

     - name: Login to Azure
       uses: azure/login@v2
       with:
         creds: ${{ secrets.AZURE_CREDENTIALS }}

     - name: Deploy to Azure Web App
       id: deploy-to-webapp
       uses: azure/webapps-deploy@v3
       with:
         app-name: 'app-jhooa-website-weu'
         slot-name: 'Production'
         package: .