name: Deploy_WebApp
on:
  workflow_dispatch:
  workflow_run:
    workflows: [Build_WebApp]
    types: [completed]
    branches: [main]

env:
  AZURE_WEBAPP_NAME: 'wapp-jhooa-weu-001'   

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    
    permissions:
      id-token: write 
      contents: write
      pull-requests: write
      repository-projects: write
    
    steps:
     - name: Download artifact from build job
       uses: dawidd6/action-download-artifact@v6
       with:
         name: release-webapp
         github-token: ${{ github.token }}
         run-id: ${{ github.event.workflow_run.id }}

     - name: Login to Azure
       uses: azure/login@v2
       with:
         client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_572FA4BE3A824385BD512120B0E996EE }}
         tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_682077AEA390487684FF940BABE5CB57 }}
         subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_E7A5BF78E2DD4DAFAC2A5E3ACF698056 }}

     - name: Deploy to Azure Web App
       id: deploy-to-webapp
       uses: azure/webapps-deploy@v3
       with:
         app-name: ${{ env.AZURE_WEBAPP_NAME }}
         slot-name: 'Production'
         package: .